
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action AuthenticateAction;
	private global::Gtk.Action Action;
	private global::Gtk.Action Action11;
	private global::Gtk.Action ActionRenew;
	private global::Gtk.Action UserStreamAction;
	private global::Gtk.Action ActionStartUSt;
	private global::Gtk.Action ActionStopUSt;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.Label lblMe;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry entTweet;
	private global::Gtk.Button btnUpdate;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView nodeview1;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label lblstatus;
	private global::Gtk.Label lblUserStream;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.AuthenticateAction = new global::Gtk.Action ("AuthenticateAction", global::Mono.Unix.Catalog.GetString ("Authenticate"), null, null);
		this.AuthenticateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Authenticate");
		w1.Add (this.AuthenticateAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString (" 認証"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString (" 認証");
		w1.Add (this.Action, null);
		this.Action11 = new global::Gtk.Action ("Action11", global::Mono.Unix.Catalog.GetString (" Action"), null, null);
		this.Action11.ShortLabel = global::Mono.Unix.Catalog.GetString (" Action");
		w1.Add (this.Action11, null);
		this.ActionRenew = new global::Gtk.Action ("ActionRenew", global::Mono.Unix.Catalog.GetString ("更新"), null, null);
		this.ActionRenew.ShortLabel = global::Mono.Unix.Catalog.GetString ("更新");
		w1.Add (this.ActionRenew, null);
		this.UserStreamAction = new global::Gtk.Action ("UserStreamAction", global::Mono.Unix.Catalog.GetString ("UserStream"), null, null);
		this.UserStreamAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("UserStream");
		w1.Add (this.UserStreamAction, null);
		this.ActionStartUSt = new global::Gtk.Action ("ActionStartUSt", global::Mono.Unix.Catalog.GetString ("Start"), null, null);
		this.ActionStartUSt.ShortLabel = global::Mono.Unix.Catalog.GetString ("Start");
		w1.Add (this.ActionStartUSt, null);
		this.ActionStopUSt = new global::Gtk.Action ("ActionStopUSt", global::Mono.Unix.Catalog.GetString ("Stop"), null, null);
		this.ActionStopUSt.Sensitive = false;
		this.ActionStopUSt.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
		w1.Add (this.ActionStopUSt, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("StarlitTwitGtk#");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar3'><menu name='FileAction' action='FileAction'/><menu name='AuthenticateAction' action='AuthenticateAction'><menuitem name='Action' action='Action'/></menu><menu name='Action11' action='Action11'><menuitem name='ActionRenew' action='ActionRenew'/></menu><menu name='UserStreamAction' action='UserStreamAction'><menuitem name='ActionStartUSt' action='ActionStartUSt'/><menuitem name='ActionStopUSt' action='ActionStopUSt'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox2.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lblMe = new global::Gtk.Label ();
		this.lblMe.Name = "lblMe";
		this.lblMe.Xalign = 0F;
		this.lblMe.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
		this.vbox2.Add (this.lblMe);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblMe]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entTweet = new global::Gtk.Entry ();
		this.entTweet.CanFocus = true;
		this.entTweet.Name = "entTweet";
		this.entTweet.IsEditable = true;
		this.entTweet.InvisibleChar = '●';
		this.hbox1.Add (this.entTweet);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entTweet]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnUpdate = new global::Gtk.Button ();
		this.btnUpdate.CanFocus = true;
		this.btnUpdate.Name = "btnUpdate";
		this.btnUpdate.UseUnderline = true;
		this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update");
		this.hbox1.Add (this.btnUpdate);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUpdate]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView ();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add (this.nodeview1);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w8.Position = 3;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.lblstatus = new global::Gtk.Label ();
		this.lblstatus.Name = "lblstatus";
		this.lblstatus.Xalign = 0F;
		this.lblstatus.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
		this.statusbar1.Add (this.lblstatus);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblstatus]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.lblUserStream = new global::Gtk.Label ();
		this.lblUserStream.Name = "lblUserStream";
		this.lblUserStream.Xalign = 1F;
		this.lblUserStream.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
		this.statusbar1.Add (this.lblUserStream);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblUserStream]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar1]));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 672;
		this.DefaultHeight = 419;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Action.Activated += new global::System.EventHandler (this.OnActionActivated);
		this.ActionRenew.Activated += new global::System.EventHandler (this.OnActionRenewActivated);
		this.ActionStartUSt.Activated += new global::System.EventHandler (this.OnActionStartUStActivated);
		this.ActionStopUSt.Activated += new global::System.EventHandler (this.OnActionStopUStActivated);
		this.entTweet.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnEntTweetKeyPressEvent);
		this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
	}
}
